---
title: "Milestone_01"
author: "Margot"
date: "28/02/2020"
output: html_document
---
```{r}
library(tidyverse)
library(here)
library(broom)
library(glue)
library(plotly)
library(viridis)
```

## Load data

```{r}
df<-read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00381/PRSA_data_2010.1.1-2014.12.31.csv")
```

## Exploratory data analysis

```{r}
str(df)
```


```{r}
sum(is.na(df$pm2.5))/length(df$pm2.5)
```
So, there are 4.73% missing values in the pm2.5 variable, which shows the data quality is reasonably good.

```{r}
df<- na.omit(df)
```




```{r}
df %>% ggplot(aes(pm2.5))+
  geom_histogram()
```


```{r}
plot_ly(x=df$month, y=df$hour, z=df$pm2.5, colors="Reds", type = "heatmap")
```


```{r}
ggplot(df, aes(month,hour, fill=pm2.5))+
  geom_tile()+
  scale_fill_gradient(low="white", high="red")
```
```{r}
p <-ggplot(df,aes(day,hour,fill=pm2.5))+
  geom_tile(color= "white",size=0.1) + 
  scale_fill_viridis(name="Hrly Temps C",option ="C")
p <-p + facet_grid(year~month)
p <-p + scale_y_continuous(trans = "reverse", breaks = unique(df$hour))
p <-p + scale_x_continuous(breaks =c(1,10,20,31))
p <-p + theme_minimal(base_size = 8)
p <-p + labs(title= "Hourly pm2.5", x="Day", y="Hour Commencing")
p <-p + theme(legend.position = "bottom")
```

